#!/usr/bin/env python3
"""
Build stage-2 AI gate feature tables by joining:
- result bag streams (/kf_gins/gps/fix, /kf_gins/odom_pred, /kf_gins/nis)
- stage-1 label CSV generated by build_ai_gate_dataset.py

This produces a tabular dataset for ML prototyping (XGBoost/MLP) without touching
runtime C++ code.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import yaml
from rclpy.serialization import deserialize_message
from rosbag2_py import ConverterOptions, SequentialReader, StorageOptions
from rosidl_runtime_py.utilities import get_message


ROOT = Path(__file__).resolve().parents[1]  # src/KF-GINS
WORKSPACE = ROOT.parents[1]


def resolve_workspace_path(p: str) -> Path:
    pp = Path(p)
    return pp if pp.is_absolute() else WORKSPACE / pp


def load_yaml(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def open_reader(bag_path: Path) -> SequentialReader:
    r = SequentialReader()
    r.open(
        StorageOptions(uri=str(bag_path), storage_id="sqlite3"),
        ConverterOptions(input_serialization_format="cdr", output_serialization_format="cdr"),
    )
    return r


def bag_topic_types(reader: SequentialReader) -> Dict[str, str]:
    return {t.name: t.type for t in reader.get_all_topics_and_types()}


def ll_to_local_xy(lat_deg: float, lon_deg: float, lat0_deg: float, lon0_deg: float) -> Tuple[float, float]:
    # simple equirectangular approximation, sufficient for short-range jump features
    r = 6378137.0
    lat = math.radians(lat_deg)
    lon = math.radians(lon_deg)
    lat0 = math.radians(lat0_deg)
    lon0 = math.radians(lon0_deg)
    x = (lon - lon0) * math.cos(0.5 * (lat + lat0)) * r
    y = (lat - lat0) * r
    return x, y


def msg_time_sec(msg: Any, bag_t_sec: float) -> float:
    header = getattr(msg, "header", None)
    if header is None:
        return bag_t_sec
    stamp = getattr(header, "stamp", None)
    if stamp is None:
        return bag_t_sec
    sec = float(getattr(stamp, "sec", 0))
    nsec = float(getattr(stamp, "nanosec", 0))
    t = sec + nsec * 1e-9
    # Fallback if header stamp is empty/zero.
    return t if t > 0 else bag_t_sec


@dataclass
class GpsFixSample:
    t: float
    status: int
    hstd: float
    vstd: float
    x: float
    y: float
    jump_xy: float
    jump_speed_xy: float
    dt: float


@dataclass
class OdomSample:
    t: float
    speed_xy: float


@dataclass
class NisSample:
    t: float
    value: float


def read_streams(
    bag_path: Path,
    gps_topic: str = "/kf_gins/gps/fix",
    odom_topic: str = "/kf_gins/odom_pred",
    nis_topic: str = "/kf_gins/nis",
) -> Tuple[List[GpsFixSample], List[OdomSample], List[NisSample]]:
    reader = open_reader(bag_path)
    types = bag_topic_types(reader)
    for t in [gps_topic, odom_topic, nis_topic]:
        if t not in types:
            raise RuntimeError(f"Topic not found in bag: {t}")

    gps_type = get_message(types[gps_topic])
    odom_type = get_message(types[odom_topic])
    nis_type = get_message(types[nis_topic])

    gps_list: List[GpsFixSample] = []
    odom_list: List[OdomSample] = []
    nis_list: List[NisSample] = []

    lat0 = lon0 = None
    prev_gps_t = None
    prev_gps_xy = None

    nis_ema = None  # only used later in lookup; placeholder here for conceptual symmetry
    _ = nis_ema

    while reader.has_next():
        topic, data, t_ns = reader.read_next()
        bag_t = t_ns * 1e-9
        if topic == gps_topic:
            msg = deserialize_message(data, gps_type)
            t = msg_time_sec(msg, bag_t)
            lat = float(msg.latitude)
            lon = float(msg.longitude)
            cov = list(msg.position_covariance)
            hstd = math.sqrt(max(cov[0], 0.0) + max(cov[4], 0.0)) / math.sqrt(2.0)
            vstd = math.sqrt(max(cov[8], 0.0))
            status = int(msg.status.status)
            if lat0 is None:
                lat0, lon0 = lat, lon
            x, y = ll_to_local_xy(lat, lon, lat0, lon0)
            if prev_gps_t is None:
                dt = 0.0
                jump_xy = 0.0
                jump_speed_xy = 0.0
            else:
                dt = max(t - prev_gps_t, 0.0)
                jump_xy = math.hypot(x - prev_gps_xy[0], y - prev_gps_xy[1])
                jump_speed_xy = (jump_xy / dt) if dt > 1e-6 else 0.0
            gps_list.append(
                GpsFixSample(
                    t=t,
                    status=status,
                    hstd=hstd,
                    vstd=vstd,
                    x=x,
                    y=y,
                    jump_xy=jump_xy,
                    jump_speed_xy=jump_speed_xy,
                    dt=dt,
                )
            )
            prev_gps_t = t
            prev_gps_xy = (x, y)
        elif topic == odom_topic:
            msg = deserialize_message(data, odom_type)
            t = msg_time_sec(msg, bag_t)
            vx = float(msg.twist.twist.linear.x)
            vy = float(msg.twist.twist.linear.y)
            odom_list.append(OdomSample(t=t, speed_xy=math.hypot(vx, vy)))
        elif topic == nis_topic:
            msg = deserialize_message(data, nis_type)
            nis_list.append(NisSample(t=bag_t, value=float(msg.data)))

    return gps_list, odom_list, nis_list


def load_label_csv(path: Path) -> List[Dict[str, Any]]:
    out = []
    with path.open("r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            out.append(
                {
                    "dataset": row["dataset"],
                    "t_rel_sec": float(row["t_rel_sec"]),
                    "err_xy": float(row["err_xy"]),
                    "err_pz": float(row["err_pz"]),
                    "err_pos_norm": float(row["err_pos_norm"]),
                    "err_vel_norm": float(row["err_vel_norm"]),
                    "label": row["label"],
                }
            )
    return out


def nearest_index(times: np.ndarray, t: float, max_dt: float) -> int:
    if times.size == 0:
        return -1
    i = int(np.searchsorted(times, t))
    cand = []
    if i < len(times):
        cand.append(i)
    if i > 0:
        cand.append(i - 1)
    if not cand:
        return -1
    j = min(cand, key=lambda k: abs(times[k] - t))
    return j if abs(times[j] - t) <= max_dt else -1


def previous_index(times: np.ndarray, t: float, max_age: float) -> int:
    if times.size == 0:
        return -1
    i = int(np.searchsorted(times, t)) - 1
    if i < 0:
        return -1
    return i if (t - times[i]) <= max_age else -1


def build_feature_table(
    labels: List[Dict[str, Any]],
    gps: List[GpsFixSample],
    odom: List[OdomSample],
    nis: List[NisSample],
    gps_match_max_dt: float = 0.2,
    odom_match_max_dt: float = 0.05,
    nis_prev_max_age: float = 5.0,
    nis_align_mode: str = "auto",
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    gps_t = np.array([s.t for s in gps], dtype=float)
    odom_t = np.array([s.t for s in odom], dtype=float)
    nis_t = np.array([s.t for s in nis], dtype=float)

    nis_vals = np.array([s.value for s in nis], dtype=float)
    nis_ema = np.empty_like(nis_vals)
    alpha = 0.2
    for i, v in enumerate(nis_vals):
        nis_ema[i] = v if i == 0 else alpha * v + (1 - alpha) * nis_ema[i - 1]

    rows: List[Dict[str, Any]] = []
    misses = {"gps": 0, "odom": 0, "nis": 0}
    nis_hits_timestamp = 0
    for lb in labels:
        t = lb["t_rel_sec"]
        gi = nearest_index(gps_t, t, gps_match_max_dt)
        oi = nearest_index(odom_t, t, odom_match_max_dt)
        ni = previous_index(nis_t, t, nis_prev_max_age)

        if gi < 0:
            misses["gps"] += 1
        if oi < 0:
            misses["odom"] += 1
        if ni < 0:
            misses["nis"] += 1
        else:
            nis_hits_timestamp += 1

        g = gps[gi] if gi >= 0 else None
        o = odom[oi] if oi >= 0 else None

        row = {
            "t_rel_sec": t,
            "label": lb["label"],
            "target_err_xy": lb["err_xy"],
            "target_err_pos_norm": lb["err_pos_norm"],
            "target_err_pz": lb["err_pz"],
            "target_err_vel_norm": lb["err_vel_norm"],
            # GNSS quality features
            "gnss_status": g.status if g else math.nan,
            "hstd_m": g.hstd if g else math.nan,
            "vstd_m": g.vstd if g else math.nan,
            "gnss_dt_sec": g.dt if g else math.nan,
            "gnss_jump_xy_m": g.jump_xy if g else math.nan,
            "gnss_jump_speed_xy_mps": g.jump_speed_xy if g else math.nan,
            # Filter consistency features
            "nis_last": float(nis_vals[ni]) if ni >= 0 else math.nan,
            "nis_ema": float(nis_ema[ni]) if ni >= 0 else math.nan,
            # Motion features (from KF odom)
            "odom_speed_xy_mps": o.speed_xy if o else math.nan,
            # Placeholders for future richer extraction
            "innovation_xy_norm": math.nan,
            "accepted_update_ratio_recent": math.nan,
            "yaw_rate_rps": math.nan,
            "acc_norm_mps2": math.nan,
            "acc_xy_std_recent": math.nan,
        }
        rows.append(row)

    # Fallback / explicit sequence-alignment for NIS when timestamp bases differ.
    # Typical case: odom/gps use header stamp (sensor/measurement time), while /kf_gins/nis
    # may use bag/write time or wall time and has no header. Then timestamp matching fails.
    use_seq_align = False
    if nis_align_mode == "sequence":
        use_seq_align = True
    elif nis_align_mode == "auto":
        if len(rows) > 0 and nis_hits_timestamp / len(rows) < 0.2 and len(nis) > 0:
            use_seq_align = True

    seq_assigned = 0
    if use_seq_align and len(nis) > 0:
        n_gps = max(len(gps), 1)
        n_nis = len(nis)
        # Monotonic sequence mapping: map matched GPS event index to approximate NIS event index.
        # This is a coarse but practical fallback for feature bootstrapping.
        for r in rows:
            # reconstruct gps index by nearest timestamp from row t (header-time domain)
            gi = nearest_index(gps_t, r["t_rel_sec"], gps_match_max_dt)
            if gi < 0:
                continue
            if n_gps == 1 or n_nis == 1:
                ni = 0
            else:
                frac = gi / float(n_gps - 1)
                ni = int(round(frac * (n_nis - 1)))
                ni = max(0, min(n_nis - 1, ni))
            r["nis_last"] = float(nis_vals[ni])
            r["nis_ema"] = float(nis_ema[ni])
            seq_assigned += 1

    summary = {
        "rows": len(rows),
        "label_counts": {
            k: int(sum(1 for r in rows if r["label"] == k)) for k in ["reliable", "uncertain", "unreliable"]
        },
        "misses": misses,
        "nis_align_mode": nis_align_mode,
        "nis_timestamp_hits": nis_hits_timestamp,
        "nis_sequence_fallback_used": use_seq_align,
        "nis_sequence_assigned": seq_assigned,
        "gps_match_max_dt": gps_match_max_dt,
        "odom_match_max_dt": odom_match_max_dt,
        "nis_prev_max_age": nis_prev_max_age,
    }
    return rows, summary


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise RuntimeError("No feature rows to write")
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default="src/KF-GINS/docs/ai_gating_design/dataset_sources.yaml")
    ap.add_argument("--dataset", required=True)
    ap.add_argument("--gps-topic", default="/kf_gins/gps/fix")
    ap.add_argument("--odom-topic", default="/kf_gins/odom_pred")
    ap.add_argument("--nis-topic", default="/kf_gins/nis")
    ap.add_argument("--gps-match-max-dt", type=float, default=0.2)
    ap.add_argument("--odom-match-max-dt", type=float, default=0.05)
    ap.add_argument("--nis-prev-max-age", type=float, default=5.0)
    ap.add_argument("--label-csv", default="", help="Optional label CSV path override")
    ap.add_argument("--output-tag", default="", help="Suffix for output feature files")
    ap.add_argument(
        "--nis-align-mode",
        choices=["auto", "timestamp", "sequence"],
        default="auto",
        help="How to align /kf_gins/nis to labeled samples. 'auto' falls back to sequence when timestamp alignment fails.",
    )
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    src_cfg = load_yaml(resolve_workspace_path(args.source))
    ds = src_cfg["datasets"][args.dataset]

    build_dir = resolve_workspace_path(ds["build_out_dir"])
    if args.label_csv:
        label_csv = resolve_workspace_path(args.label_csv)
    else:
        label_csv = build_dir / "ai_gate_label_samples.csv"
    if not label_csv.exists():
        raise SystemExit(f"Label CSV not found. Run build_ai_gate_dataset.py first: {label_csv}")

    bag_path = resolve_workspace_path(ds["bag"])
    gps, odom, nis = read_streams(bag_path, args.gps_topic, args.odom_topic, args.nis_topic)
    labels = load_label_csv(label_csv)

    rows, summary = build_feature_table(
        labels=labels,
        gps=gps,
        odom=odom,
        nis=nis,
        gps_match_max_dt=args.gps_match_max_dt,
        odom_match_max_dt=args.odom_match_max_dt,
        nis_prev_max_age=args.nis_prev_max_age,
        nis_align_mode=args.nis_align_mode,
    )

    suffix = f"_{args.output_tag}" if args.output_tag else ""
    feat_csv = build_dir / f"ai_gate_features{suffix}.csv"
    feat_summary = build_dir / f"ai_gate_features_summary{suffix}.json"
    write_csv(feat_csv, rows)

    extra = {
        "dataset": args.dataset,
        "bag": ds["bag"],
        "label_csv": str(label_csv),
        "feature_csv": str(feat_csv),
        "gps_topic": args.gps_topic,
        "odom_topic": args.odom_topic,
        "nis_topic": args.nis_topic,
        "stream_counts": {"gps": len(gps), "odom": len(odom), "nis": len(nis)},
    }
    out = {**extra, **summary}
    with feat_summary.open("w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)

    print("[DONE] AI gate features generated")
    print(json.dumps(out, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
