#!/usr/bin/env python3
"""
Train an AI-assisted GNSS gate classifier using XGBoost.

Input:
- one or more feature CSV files generated by `build_ai_gate_features.py`

Output:
- XGBoost model (.json)
- metrics.json
- feature_importance.csv

This script prefers sklearn for split/metrics when available, and falls back to
internal implementations if needed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List

import numpy as np
import pandas as pd

try:
    import xgboost as xgb
except Exception as e:  # pragma: no cover
    raise SystemExit(
        "xgboost is required. Install it first, e.g. `python3 -m pip install --user xgboost`.\n"
        f"Import error: {e}"
    )

try:
    from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix
    from sklearn.model_selection import train_test_split

    HAVE_SKLEARN = True
except Exception:
    HAVE_SKLEARN = False


DEFAULT_FEATURES = [
    "gnss_status",
    "hstd_m",
    "vstd_m",
    "gnss_dt_sec",
    "gnss_jump_xy_m",
    "gnss_jump_speed_xy_mps",
    "odom_speed_xy_mps",
    "nis_last",
    "nis_ema",
]


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--inputs",
        nargs="+",
        default=[
            "src/KF-GINS/results/ai_gate_dataset/test_demo/ai_gate_features.csv",
            "src/KF-GINS/results/ai_gate_dataset/urbannav_hk_tunnel1/ai_gate_features.csv",
        ],
        help="Feature CSV paths",
    )
    ap.add_argument(
        "--out-dir",
        default="src/KF-GINS/results/ai_gate_model_xgboost",
        help="Output directory",
    )
    ap.add_argument(
        "--drop-uncertain",
        action="store_true",
        default=True,
        help="Drop uncertain labels (default true)",
    )
    ap.add_argument("--test-ratio", type=float, default=0.2)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--num-round", type=int, default=300)
    ap.add_argument("--max-depth", type=int, default=4)
    ap.add_argument("--eta", type=float, default=0.05)
    ap.add_argument("--subsample", type=float, default=0.8)
    ap.add_argument("--colsample-bytree", type=float, default=0.8)
    ap.add_argument(
        "--features",
        nargs="*",
        default=DEFAULT_FEATURES,
        help="Feature columns to use",
    )
    return ap.parse_args()


def _safe_numeric(df: pd.DataFrame, cols: List[str]) -> pd.DataFrame:
    out = df.copy()
    for c in cols:
        out[c] = pd.to_numeric(out[c], errors="coerce")
    return out


def load_and_merge(paths: List[str]) -> pd.DataFrame:
    dfs = []
    for p in paths:
        pp = Path(p)
        if not pp.exists():
            raise SystemExit(f"Input not found: {pp}")
        df = pd.read_csv(pp)
        dfs.append(df)
    return pd.concat(dfs, ignore_index=True)


def encode_labels(df: pd.DataFrame) -> pd.DataFrame:
    # Binary v1: reliable=1, unreliable=0; uncertain optional drop
    if "label" not in df.columns:
        raise SystemExit("Missing label column")
    if "uncertain" in set(df["label"].astype(str)):
        df = df[df["label"] != "uncertain"].copy()
    df["y"] = (df["label"].astype(str) == "reliable").astype(int)
    return df


def stratified_split_indices(y: np.ndarray, test_ratio: float, seed: int):
    rng = np.random.default_rng(seed)
    idx_pos = np.where(y == 1)[0]
    idx_neg = np.where(y == 0)[0]
    rng.shuffle(idx_pos)
    rng.shuffle(idx_neg)
    n_pos_test = max(1, int(round(len(idx_pos) * test_ratio))) if len(idx_pos) > 1 else len(idx_pos)
    n_neg_test = max(1, int(round(len(idx_neg) * test_ratio))) if len(idx_neg) > 1 else len(idx_neg)
    test_idx = np.concatenate([idx_pos[:n_pos_test], idx_neg[:n_neg_test]])
    train_mask = np.ones(len(y), dtype=bool)
    train_mask[test_idx] = False
    train_idx = np.where(train_mask)[0]
    rng.shuffle(train_idx)
    rng.shuffle(test_idx)
    return train_idx, test_idx


def confusion_and_metrics(y_true: np.ndarray, y_prob: np.ndarray, thr: float = 0.5):
    y_pred = (y_prob >= thr).astype(int)
    tp = int(np.sum((y_true == 1) & (y_pred == 1)))
    tn = int(np.sum((y_true == 0) & (y_pred == 0)))
    fp = int(np.sum((y_true == 0) & (y_pred == 1)))
    fn = int(np.sum((y_true == 1) & (y_pred == 0)))
    acc = (tp + tn) / max(1, len(y_true))
    prec = tp / max(1, tp + fp)
    rec = tp / max(1, tp + fn)
    f1 = 2 * prec * rec / max(1e-12, prec + rec)

    # AUC (rank-based) without sklearn
    order = np.argsort(y_prob)
    ranks = np.empty_like(order, dtype=float)
    ranks[order] = np.arange(1, len(y_prob) + 1)
    pos = y_true == 1
    n_pos = int(np.sum(pos))
    n_neg = int(len(y_true) - n_pos)
    if n_pos > 0 and n_neg > 0:
        auc = (np.sum(ranks[pos]) - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg)
    else:
        auc = float("nan")

    return {
        "threshold": thr,
        "accuracy": acc,
        "precision": prec,
        "recall": rec,
        "f1": f1,
        "auc": float(auc),
        "confusion": {"tp": tp, "tn": tn, "fp": fp, "fn": fn},
    }


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df = load_and_merge(args.inputs)
    df = encode_labels(df)
    feature_cols = [c for c in args.features if c in df.columns]
    if not feature_cols:
        raise SystemExit("No requested feature columns found in inputs")
    df = _safe_numeric(df, feature_cols + ["y"])
    # Simple imputation: fill NaN with column median
    medians = {c: float(df[c].median(skipna=True)) if not df[c].dropna().empty else 0.0 for c in feature_cols}
    for c in feature_cols:
        df[c] = df[c].fillna(medians[c])

    X = df[feature_cols].to_numpy(dtype=np.float32)
    y = df["y"].to_numpy(dtype=np.int32)
    if HAVE_SKLEARN:
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=args.test_ratio, random_state=args.seed, stratify=y
        )
        train_idx = np.arange(len(X_train))
        test_idx = np.arange(len(X_test))
    else:
        train_idx, test_idx = stratified_split_indices(y, args.test_ratio, args.seed)
        X_train, y_train = X[train_idx], y[train_idx]
        X_test, y_test = X[test_idx], y[test_idx]

    dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=feature_cols)
    dtest = xgb.DMatrix(X_test, label=y_test, feature_names=feature_cols)

    pos = int(np.sum(y_train == 1))
    neg = int(np.sum(y_train == 0))
    scale_pos_weight = (neg / pos) if pos > 0 else 1.0

    params = {
        "objective": "binary:logistic",
        "eval_metric": ["logloss", "auc"],
        "eta": args.eta,
        "max_depth": args.max_depth,
        "subsample": args.subsample,
        "colsample_bytree": args.colsample_bytree,
        "tree_method": "hist",
        "seed": args.seed,
        "scale_pos_weight": scale_pos_weight,
    }

    evals_result = {}
    booster = xgb.train(
        params=params,
        dtrain=dtrain,
        num_boost_round=args.num_round,
        evals=[(dtrain, "train"), (dtest, "test")],
        evals_result=evals_result,
        verbose_eval=False,
    )

    y_prob = booster.predict(dtest)
    if HAVE_SKLEARN:
        y_pred = (y_prob >= 0.5).astype(int)
        tn, fp, fn, tp = confusion_matrix(y_test, y_pred, labels=[0, 1]).ravel()
        metrics = {
            "threshold": 0.5,
            "accuracy": float(accuracy_score(y_test, y_pred)),
            "precision": float(precision_score(y_test, y_pred, zero_division=0)),
            "recall": float(recall_score(y_test, y_pred, zero_division=0)),
            "f1": float(f1_score(y_test, y_pred, zero_division=0)),
            "auc": float(roc_auc_score(y_test, y_prob)) if len(np.unique(y_test)) > 1 else float("nan"),
            "confusion": {"tp": int(tp), "tn": int(tn), "fp": int(fp), "fn": int(fn)},
        }
    else:
        metrics = confusion_and_metrics(y_test, y_prob, thr=0.5)

    model_path = out_dir / "xgboost_ai_gate_model.json"
    booster.save_model(model_path)

    fi_gain = booster.get_score(importance_type="gain")
    fi_weight = booster.get_score(importance_type="weight")
    fi_rows = []
    for f in feature_cols:
        fi_rows.append(
            {
                "feature": f,
                "gain": float(fi_gain.get(f, 0.0)),
                "weight": float(fi_weight.get(f, 0.0)),
                "median_impute": medians[f],
            }
        )
    fi_df = pd.DataFrame(fi_rows).sort_values("gain", ascending=False)
    fi_path = out_dir / "feature_importance.csv"
    fi_df.to_csv(fi_path, index=False)

    summary = {
        "inputs": args.inputs,
        "out_dir": str(out_dir),
        "feature_cols": feature_cols,
        "n_total": int(len(df)),
        "n_train": int(len(train_idx)),
        "n_test": int(len(test_idx)),
        "label_counts_total": {
            "reliable": int(np.sum(y == 1)),
            "unreliable": int(np.sum(y == 0)),
        },
        "params": params,
        "num_round": args.num_round,
        "use_sklearn": HAVE_SKLEARN,
        "metrics_test": metrics,
        "model_path": str(model_path),
        "feature_importance_csv": str(fi_path),
        "evals_result_tail": {
            "train": {k: float(v[-1]) for k, v in evals_result.get("train", {}).items()},
            "test": {k: float(v[-1]) for k, v in evals_result.get("test", {}).items()},
        },
    }
    with (out_dir / "metrics.json").open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    print("[DONE] XGBoost AI gate model trained")
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
